import Head from 'next/head';
import Link from 'next/link';
import About from '../components/About';
import ContactMe from '../components/ContactMe';
import Experience from '../components/Experience';
import Header from '../components/Header';
import Hero from '../components/Hero';
import Projects from '../components/Projects';
import Skills from '../components/Skills';
import { HomeIcon } from "@heroicons/react/24/solid";

export default function Home() {
  return (
    <>
      <div className="h-screen text-white bg-gradient-to-t from-gray-700 via-gray-900 to-black snap-y snap-mandatory overflow-y-scroll overflow-x-hidden scrollbar scrollbar-track-gary-400/20 scrollbar-thumb-cyan-400/80 z-0">
      <Head>
        <title>Aditya Kasralkar - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Hero */}
      <section id="hero" className="snap-start">
        <Hero />
      </section>

      {/* About */}
      <section id="about" className="snap-center">
        <About />
      </section>

      {/* Experience */}
      <section id="experience" className="snap-center">
        <Experience/>
      </section>

      {/* Skills */}
      <section id="skills" className="snap-start">
        <Skills />
      </section>

      {/* Projects */}
      <section id="projects" className="snap-start">
        <Projects />
      </section>

      {/* Contact Me */}
        <section id="contact" className="snap-start">
          <ContactMe />
        </section>

        <Link href="#hero">
          <footer className="sticky bottom-5 w-full cursor-pointer">
            <div className="flex items-center justify-end pr-16">
              <HomeIcon className="h-6 w-6 opacity-75 hover:opacity-100" />
            </div>
          </footer>
        </Link>

      </div>
    </>
  )
}
